name: Build CI

permissions:
  contents: write

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
  
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          out/axvm-bios.bin
